// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwphesbffgjhzqnijkmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3cGhlc2JmZmdqaHpxbmlqa21qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMzM4ODksImV4cCI6MjA2NTYwOTg4OX0.uLYe1Isjc6EnnS5i_mTvYZ4p5X_Rcoj4-5WbxmiVRW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);